
// import HeaderNav from "./components/assets/HeaderNav";
import Footer from "./assets/Footer";
import HeaderNav from "./assets/HeaderNav";
import { AppProvider } from "./context/AppProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <AppProvider>
          <HeaderNav />
          {children}
          <Footer/>
        </AppProvider>
      </body>
    </html>
  );
}
